### ISSUE TITLE
Is there any chance for the intel i226-v driver port to the kernel 4.14.275 (OpenWrt 19.07.x) ?

### ISSUE THREAD

**Issue by fox85** [csrutil/realtek-r8125-openwrt#8]
First, thanks for the GREAT job 👍  ,  the r8125b 2.5G NIC works very well on my X86 Router (OpenWrt 19.07.10).
Now I'm going to buy another machine :
( https://cwwk.net/products/the-12th-generation-u-series-small-and-large-core-mixed-architecture-mini-host )
It is built in with 6  intel i226-v  NIC.
For some reason, I'd like to run OpenWrt 19.07.10, because the kernel 4.14.275 is more stable than the kernel 5.x .
Could you please compile a driver  ipk for the OpenWrt 19.07.x with intel i226-v NIC ?
Thank you very much.

**Comment by fox85** [comment]
PS:
according to this post:
https://github.com/openwrt/openwrt/issues/10567
I226-V should be supported in kernel v5.10 (22.03~), via kmod-igc, but not v5.4 (21.02.x and earlier).

**Comment by csrutil** [comment]
Yeah, I think the best approach is to use the latest OpenWrt for the intel i226. The NIC is buggy
